CREATE DATABASE PRODUOTEX
GO
USE PRODUOTEX
GO
CREATE TABLE PRODUTO(
CODIGO			INT				NOT NULL,
NOME			VARCHAR(30)		NOT NULL,
VALOR_UNITARIO	NUMERIC(7,2)	NOT NULL,
QTD_ESTOQUE		INT				NOT NULL
PRIMARY KEY (CODIGO)
)
GO
INSERT INTO PRODUTO 
VALUES
(1,'PROD01',12.4,20),
(2,'PROD02',12.4,2),
(3,'PROD03',12.4,34),
(4,'PROD04',12.4,90)
GO
SELECT * FROM PRODUTO
GO
CREATE FUNCTION FN_BUSCP(@QTD INT)
RETURNS INT
AS
	BEGIN 
		DECLARE @RES INT
		SET @RES = (SELECT COUNT(P.CODIGO) FROM PRODUTO P WHERE P.QTD_ESTOQUE < @QTD)
		RETURN @RES
	END
GO
SELECT dbo.FN_BUSCP(40) AS FUNC
GO
CREATE FUNCTION FN_LISTP(@QTD INT)
RETURNS @TABPRO TABLE(
CODIGO	INT				NOT NULL,
NOME	VARCHAR(30)		NOT NULL,
PQTD	INT				NOT NULL
)
AS
	BEGIN
		INSERT INTO @TABPRO (CODIGO,NOME,PQTD) SELECT P.CODIGO,P.NOME,P.QTD_ESTOQUE FROM 
		PRODUTO P WHERE P.CODIGO IN (
			SELECT P.CODIGO FROM PRODUTO P WHERE P.QTD_ESTOQUE < @QTD
		)
		RETURN
	END
GO
SELECT CODIGO, NOME, PQTD FROM FN_LISTP(135)
GO
-----------------------------------------------------
INSERT INTO PRODUTO VALUES (5,'PROD05',15.4,25)
GO
UPDATE PRODUTO
SET NOME = 'BOLDER', VALOR_UNITARIO = 500.90, QTD_ESTOQUE = 12
WHERE PRODUTO.CODIGO = 5
GO
DELETE PRODUTO WHERE PRODUTO.CODIGO = 5
GO
SELECT P.CODIGO,P.NOME,P.VALOR_UNITARIO,P.QTD_ESTOQUE FROM PRODUTO P
GO
SELECT * FROM PRODUTO
